### ISSUE TITLE
ScreenCapture feature in controller ionicitude.

### ISSUE THREAD

**Issue by GeoffSeloana** [Tazaf/IonicitudeDemoApp#1] opened 2016-07-07 13:46 UTC
Greetings
I was trying to use the Screen Capture feature but i am battling. The screen Capture feature is also not working on the Demo App. 
I see in the "capturescreen.js" file in the "6_BrowsingPois_6_Bonus-CaptureScreen" world that you are calling the captureScreen function you have created in the app.js file.

```
// The call to this Action is in www/wikitude-worlds/6_BrowsingPois_6_Bonus-CaptureScreen/js/capturescreen.js:283
function captureScreen() {
    Ionicitude.captureScreen(true, null)
      .then(function (absoluteFilePath) {
          console.log("snapshot stored at:\n" + absoluteFilePath);
      })
      .catch(function (error) {
          console.log(error);
      });
}
```

This function does not seem to work because when i press the button i still cannot see that console.log showing on the console.

**Comment by Tazaf** [comment] 2016-07-07 14:04
Hi !

Could you give more information (screenshots, error messages, if any) about the screenCapture not working in the Demo App ?
It was working during my tests.
Can you check if you have the latest Ionicitude version (^0.2.1-alpha) in the project (that should be the case, though).

**Comment by GeoffSeloana** [comment] 2016-07-07 14:23
But i just downloaded the app and followed the instructions. I ran the "ionic state restore" and it ran well and restored everything. Running the app all the functions are working besides this particular one.

**Comment by Tazaf** [comment] 2016-07-07 14:45
(You should have put your initial message's edit on a new message, I almost missed it :wink:)

When you say that you don't see the log in your console, may I ask you of which console you're talking about ?
Since there are two WebViews when an AR World is active _(one with the Ionic App - in background -, and a second with the actual AR World)_, there are also two consoles (one for each WebViews).
That particular log should appear in the console of the Ionic App WebView, since it is executed from this WebView. It should not appear in the console of the AR World WebView.

To be completely sure, you could also check your device's gallery to see if you can find your screenshot.

**Comment by GeoffSeloana** [comment] 2016-07-07 14:48
Sorry for not marking my previous message edited. I was referring to the one on the Ionic App, the one that should print out the path to the file.

**Comment by Tazaf** [comment] 2016-07-07 14:54
Ah... OK.

On which device (and OS) are you launching the app ? Is it an iPhone on iOS9 ?

(Also, did you found any screenshot in your phone's gallery ?)

**Comment by GeoffSeloana** [comment] 2016-07-08 07:49
I am launching it on a note 3, android 5.0. I do not find anything in the gallery.

**Comment by Tazaf** [comment] 2016-07-08 08:16
Hum.

It seems as if the `document.location` statement in the `capturescreen.js` is not correctly catched, as you implied...

I'd like to see if it's specific to the capture screen statement or if it's the same behavior for all `document.location` statement.

You can see [here](https://github.com/Tazaf/IonicitudeDemoApp/blob/master/www/wikitude-worlds/6_BrowsingPois_6_Bonus-CaptureScreen/js/capturescreen.js#L111) that there is a second `document.location` statement on the captureScreen AR World example.

To fire it, you need to click on a POI and then click on the "More" button. As a result, there should be a `console.log` line in the Ionic WebView console _(see attached - taken from the Ionic WebView console)_

![image](https://cloud.githubusercontent.com/assets/7702322/16681410/da2535cc-44f4-11e6-95df-9bf9ed3e5233.png)

Could you try this and tell me if anything appeared on your console ?

**Comment by GeoffSeloana** [comment] 2016-07-08 10:38
![image](https://cloud.githubusercontent.com/assets/8654757/16685047/bdbb54b6-4508-11e6-8e38-018f63e0a8ac.png)
Nothing appears on the console. None of the buttons seems to recognize the clicks

**Comment by Tazaf** [comment] 2016-07-08 11:04
In your picture, you seem to be displaying the console for the AR World WebView. If it was the console for the Ionic App, there should be the same first lines of log as seen in my previous comment (unless you manually cleaned the console ?).

I see that you are using Chrome, so you should see something like that when navigating to `chrome://inspect`:

![image](https://cloud.githubusercontent.com/assets/7702322/16685568/41ad8142-450c-11e6-9501-083931e5fbbb.png)

And the WebView you'd want to inspect is the one labelled `index.html`.

**Comment by GeoffSeloana** [comment] 2016-07-08 11:09
![image](https://cloud.githubusercontent.com/assets/8654757/16685685/03c8bdd2-450d-11e6-9537-68ef166bae84.png)
Screen capture error

**Comment by Tazaf** [comment] 2016-07-08 11:20
Okay.
I see where the problem is. It appears that the Demo App is in fact not using the latest version of Ionicitude (despite me thinking so).

Thanks (again) for pointing that out. I'll made the correction now, and push a new version of the App to close the issue.

**Closed as completed** 2016-07-08 11:21 UTC
